### PR TITLE
#62 add dark mode support for all screens

### PR DESCRIPTION
**Pull request by break2k**
Here is a PR to showcase the dark mode support i've added to the different storyboard and Theme colors who needed some adjustments:

splash
timeline
timeline_detail
mentors
mentors_detail
map
map_focus

### CODE REVIEW

**Comment by funky-monkey** [comment]
Looks good! @ppeelen can you merge this?

**Review by ppeelen — APPROVED** [review]
Looks really good! Thank you for your contribution!

**Comment by BasThomas** [comment]
🤩

**Comment by SpacyRicochet** [comment]
Nice! 🌓

**Pull request merged**
