### PR TITLE
Add support of Dynamic Type for MentorCardViewController

### LINKED ISSUE #37: Improved support Dynamic Type in the Mentor detail screen
**Is your feature request related to a problem? Please describe.**
The mentor detail screen (in the card view) does not support Dynamic Type properly. To achieve this, the following should be done;

Simulator Screen Shot - iPhone 5s - 2019-06-25 at 10 55 09

* [ ] Make the name label conform to dynamic type and allow to adjust on trait changes.
  * Take care to avoid the title label going over or under the photo. This may require a small design change (or a larger code change to cut out the photo from the text rendering.)
* [ ] Make the story label conform to dynamic type and allow to adjust on trait changes.
* [ ] Consider making the icons adjust according to text styles.
* [ ] Note that the screen should be scrollable to accomodate AXXXL text.

### PR DESCRIPTION
**Pull request by subdan**
This PR closes #37
I added Dynamic Type support for Mentor detail screen

### CODE REVIEW

**Review by ppeelen — CHANGES_REQUESTED** [review]
Nice job and thank you for your contribution! A new bug, however, became apparent now that a larger text is possible; when a mentor card is shown and the user scrolls to lower on said card, closes the card and opens another mentor's card, the next card is shown at the same scroll position.

Hence the scroll position of the scrollView needs to be reset when the card closes.

**Comment by subdan** [comment]
Ok. I'll fix it.

**Comment by subdan** [comment]
I've resolved merge conflict and fixed scroll position.

**Review by ppeelen — APPROVED** [review]

**Comment by ppeelen** [comment]
Great work! I'll let bitrise complete and then merge the PR! Thank you for your contribution!

**Pull request merged**
