### PR TITLE
The titles for bungalow names are off by a few pixels - fixed

### PR DESCRIPTION
**Pull request by spase84**
The titles vertical position for bungalow is centered.

### CODE REVIEW

**Comment by spase84** [comment]
This is solution for #28 
Tested on iOS 12 (iPhone 8Plus), iOS 13 (iPhone X) and on Simulators (iOS 12+)

**Comment by funky-monkey** [comment]
Hi @spase84, 

Great work!
I can only merge this from October 1st to make it count for #hacktoberfast.

Best, 
Sidney

**Comment by spase84** [comment]
Hi, @funky-monkey ,

Ok, thanks.

**Comment by funky-monkey** [comment]
Hi @spase84,

I just re-read the Hacktoberfest rules - it states that PR's have to be created between 1-31 oct.
```
To qualify for the official limited edition Hacktoberfest shirt, you must register and then make four pull requests (PRs) between October 1-31 (in any time zone). PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest. ...
``` 
[Source](https://hacktoberfest.digitalocean.com/details)

So for now I will decline these PR's because otherwise they don't count for you and that would be a shame. I would like to ask you re-submit the PR on October 1st.

Best,
Sidney

**Pull request closed without merging**
